apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: eurekaserver
spec:
  selector:
    matchLabels:
      app: eurekaserver
  replicas: 1 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - env:
        - name: eureka_host
          value: "eurekaserver"
        - name: eureka_port
          value: "8761"
        - name: rabbitmq_host
          value: "10.42.59.130"
        name: eurekaserver
        image: gayatri01/eurekaserver
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
  labels:
    app: eurekaserver
spec:
  type: ClusterIP
  ports:
  - port: 8761
  selector:
    app: eurekaserver
        

