apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  replicas: 1 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - env:
        - name: DB_VENDOR
          value: "MYSQL"
        - name: DB_ADDR
          value: "10.42.59.130"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "keycloak"
        - name: DB_USER
          value: "keycloak"
        - name: DB_PASSWORD
          value: "keycloak"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: KEYCLOAK_USER
          value: "admin"
        name: keycloak
        image: gayatri01/keycloak
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: keycloak
